#!/usr/bin/env node
let Program = require('commander')

Program
.version('1.0.0', '-V')
.command('user', 'for actions about users').alias('u')
.command('project', 'for actions about projects').alias('p')
.command('module', 'for actions about modules').alias('m')
.command('styleguide', 'for actions about styleguides').alias('s')
.parse(process.argv)

if (Program.args.length === 0) {
  Program.help()
}
