#!/usr/bin/env node
let Program = require('commander')
let Actions = require('./models/project')
let Errors = require('./lib/errors')

for (let action in Actions){
  Actions[action](Program).catch(Errors.errorFunc)
}

Program
.parse(process.argv)

if (Program.args.length === 0) {
  Program.help()
}
